security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    providers:
        my_provider:
            entity:
                class: App\Entity\Users
                property: username
        reg_provider:
            entity:
                class: App\Entity\Users
                property:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy

            form_login:
                login_path: login
                check_path: login
                provider: my_provider

            logout:
                path: /logout
                target: /login


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

